#!/usr/bin/env python3
"""Inherited-behaviour generator (DuckDB) for Temporal<T> subtypes.

DuckDB sibling of MobilityDB's tools/codegen/inherited/generate.py. It emits the
DuckDB scalar-function registrations that every Temporal<T> subtype inherits via
late binding + lifting (topops, and — replicating the same skeleton — posops,
compops, spatialrels, ...). The registrations are pure wiring to the family-agnostic
Gen_<op>_<direction> executors (the BLOB×BLOB→bool bridges the catalog generator
already emits), identical across families modulo the type token, so they are
generated from one template per behaviour rather than hand-registered per family.

  python tools/inherited/generate.py --check      # list what would be emitted
  python tools/inherited/generate.py --emit        # write the registration fragment
  python tools/inherited/generate.py --validate     # generated wiring == what the
                                                    # catalog generator emits today
"""
from __future__ import annotations
import argparse
import pathlib
import re
import sys

try:
    import yaml  # pyyaml
except ImportError:
    sys.exit("pyyaml is required: pip install pyyaml")

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[1]
MANIFEST = HERE / "manifest.yaml"
TEMPLATES = HERE / "templates"
# The catalog generator's output that this fragment is spliced into / validated against.
GENERATED_DIR = ROOT / "src" / "generated"
# The catalog generator emits the surface as several units, so the fragment is validated
# against all of them rather than against whichever one happens to carry a registration.
def generated_surface() -> str:
    return "\n".join(p.read_text()
                     for p in sorted(GENERATED_DIR.glob("generated_temporal_udfs*.cpp")))

BANNER = (
    "// GENERATED by tools/inherited/generate.py from templates/{tmpl}\n"
    "// DO NOT EDIT BY HAND; edit the template + tools/inherited/manifest.yaml"
    " and re-run.\n")

# The two fixed bounding-box operands shared by every tspatial family: the
# time-dimension span and the spatiotemporal box.
FIXED_FACTORIES = {"SpanTypes::tstzspan()", "StboxType::stbox()"}

REG_RE = re.compile(
    r'ScalarFunction\("([^"]+)",\s*\{\s*([\w:]+\(\)),\s*([\w:]+\(\))\s*\},'
    r'\s*LogicalType::BOOLEAN,\s*(Gen_\w+)\)')


def render(behaviour: str, sub: dict) -> str:
    tmpl = (TEMPLATES / f"{behaviour}.tmpl").read_text()
    return (tmpl.replace("@FACTORY@", sub["factory"])
                .replace("@TEMP@", sub["temp"])
                .replace("@BRIEF@", sub["brief"]))


def render_all(behaviour: str, subs: list) -> str:
    return "\n".join(render(behaviour, s) for s in subs)


def tuples(text: str) -> set:
    """(op-name, arg1, arg2, executor) registration tuples parsed from `text`."""
    return set(REG_RE.findall(text))


def generated_tuples(behaviour: str, subs: list) -> set:
    return tuples(render_all(behaviour, subs))


def committed_tuples(behaviour: str, subs: list) -> set:
    """The topological registrations the catalog generator currently emits for our
    families: keep only registrations whose executor is one of this behaviour's
    shared Gen_<op>_<direction> bridges AND both operands are a manifest family or a
    fixed box operand — i.e. exactly the surface this template owns."""
    fam_factories = {s["factory"] for s in subs}
    operands = fam_factories | FIXED_FACTORIES
    execs = {t[3] for t in generated_tuples(behaviour, subs)}
    keep = set()
    for name, a1, a2, ex in tuples(generated_surface()):
        if ex in execs and a1 in operands and a2 in operands:
            # at least one operand must be one of OUR families (exclude box×box etc.)
            if a1 in fam_factories or a2 in fam_factories:
                keep.add((name, a1, a2, ex))
    return keep


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="list what would be emitted")
    ap.add_argument("--emit", action="store_true",
                    help="write the registration fragment to src/generated/inherited/")
    ap.add_argument("--validate", action="store_true",
                    help="generated wiring == what the catalog generator emits today")
    ap.add_argument("--behaviour", default="topops", help="behaviour to generate")
    args = ap.parse_args()

    mf = yaml.safe_load(MANIFEST.read_text())
    subs = [s for s in mf["subtypes"] if s.get("category") == "tspatial"]
    beh = args.behaviour

    if args.validate:
        gen = generated_tuples(beh, subs)
        cur = committed_tuples(beh, subs)
        missing = sorted(gen - cur)   # template would emit, catalog does not
        extra = sorted(cur - gen)     # catalog emits, template would not
        print(f"[{beh}] families={len(subs)} "
              f"generated={len(gen)} committed(matched)={len(cur)}")
        for m in missing:
            print(f"  ONLY-IN-TEMPLATE {m}")
        for e in extra:
            print(f"  ONLY-IN-COMMITTED {e}")
        ok = not missing and not extra
        print("EQUIVALENT" if ok else "MISMATCH")
        return 0 if ok else 1

    body = render_all(beh, subs)
    if args.check:
        for s in subs:
            print(f"would emit {beh} wiring for {s['temp']} ({s['factory']})")
        print(f"total registrations: {len(tuples(body))}")
        return 0

    if args.emit:
        out = ROOT / "src" / "generated" / "inherited" / f"{beh}_registrations.inc"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(BANNER.format(tmpl=f"{beh}.tmpl") + "\n" + body)
        print(f"wrote {out.relative_to(ROOT)} ({len(tuples(body))} registrations)")
        return 0

    ap.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
