"""Generate covering.sql from the MEOS-API temporal-covering descriptor.

MobilityDuck's projection of the catalog `temporalCovering` block: per covering
class, a DuckDB macro that returns the TemporalParquet covering columns of a
temporal value as a STRUCT. The covering schema is therefore generated from the
single catalog source of truth, not hand-written.

    python3 tools/covering/codegen_covering.py     # -> tools/covering/covering.sql

Pure dict -> text; pin-independent to run. The emitted macros use box accessors
already present in the extension (`stbox`/`tbox`/`Xmin`/.../`SRID`).
"""

import json
from pathlib import Path

HERE = Path(__file__).parent
DESCRIPTOR = HERE / "temporal-covering.json"
OUT = HERE / "covering.sql"

# MEOS C symbol -> MobilityDuck SQL function (the binding's box-accessor map).
# The only binding-specific knowledge; everything else comes from the descriptor.
DUCK_FN = {
    "tspatial_to_stbox": "stbox", "tnumber_to_tbox": "tbox",
    "stbox_xmin": "Xmin", "stbox_xmax": "Xmax",
    "stbox_ymin": "Ymin", "stbox_ymax": "Ymax",
    "stbox_zmin": "Zmin", "stbox_zmax": "Zmax",
    "stbox_tmin": "Tmin", "stbox_tmax": "Tmax",
    "tbox_xmin": "Xmin", "tbox_xmax": "Xmax",
    "tbox_tmin": "Tmin", "tbox_tmax": "Tmax",
    "tspatial_srid": "SRID",
    "temporal_start_timestamptz": "startTimestamp",
    "temporal_end_timestamptz": "endTimestamp",
}


def _column_expr(column: dict, box_from: str) -> str:
    fn = DUCK_FN[column["accessor"]]
    if column["source"] == "value":
        return f"{fn}(t)"
    return f"{fn}({DUCK_FN[box_from]}(t))"


def build_sql(descriptor: dict) -> str:
    classes = descriptor["classes"]
    out = [
        "-- Generated by tools/covering/codegen_covering.py from the MEOS-API",
        "-- temporal-covering descriptor. Do not edit by hand; regenerate.",
        "--",
        "-- Each macro returns a temporal value's TemporalParquet covering columns",
        "-- as a STRUCT. Materialise them with:",
        "--   SELECT base.*, c.* FROM (SELECT base, covering_<class>(value) AS c FROM ...)",
        "",
    ]
    by_type = {}
    for class_name, spec in classes.items():
        box = spec.get("box")
        box_from = box["from"] if box else None
        fields = ", ".join(
            f"'{c['name']}': {_column_expr(c, box_from)}" for c in spec["columns"])
        out.append(f"CREATE OR REPLACE MACRO covering_{class_name}(t) AS {{ {fields} }};")
        for t in spec["types"]:
            by_type[t] = class_name
    out.append("")
    out.append("-- temporal type -> covering macro:")
    for t in sorted(by_type):
        out.append(f"--   {t}: covering_{by_type[t]}")
    return "\n".join(out) + "\n"


def main() -> None:
    sql = build_sql(json.loads(DESCRIPTOR.read_text()))
    OUT.write_text(sql)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
