-- Generated by tools/covering/codegen_covering.py from the MEOS-API
-- temporal-covering descriptor. Do not edit by hand; regenerate.
--
-- Each macro returns a temporal value's TemporalParquet covering columns
-- as a STRUCT. Materialise them with:
--   SELECT base.*, c.* FROM (SELECT base, covering_<class>(value) AS c FROM ...)

CREATE OR REPLACE MACRO covering_spatial(t) AS { 'xmin': Xmin(stbox(t)), 'xmax': Xmax(stbox(t)), 'ymin': Ymin(stbox(t)), 'ymax': Ymax(stbox(t)), 'zmin': Zmin(stbox(t)), 'zmax': Zmax(stbox(t)), 'tmin': Tmin(stbox(t)), 'tmax': Tmax(stbox(t)), 'srid': SRID(t) };
CREATE OR REPLACE MACRO covering_number(t) AS { 'vmin': Xmin(tbox(t)), 'vmax': Xmax(tbox(t)), 'tmin': Tmin(tbox(t)), 'tmax': Tmax(tbox(t)) };
CREATE OR REPLACE MACRO covering_timeOnly(t) AS { 'tmin': startTimestamp(t), 'tmax': endTimestamp(t) };

-- temporal type -> covering macro:
--   tbigint: covering_number
--   tbool: covering_timeOnly
--   tcbuffer: covering_spatial
--   tfloat: covering_number
--   tgeogpoint: covering_spatial
--   tgeography: covering_spatial
--   tgeometry: covering_spatial
--   tgeompoint: covering_spatial
--   tint: covering_number
--   tnpoint: covering_spatial
--   tpose: covering_spatial
--   trgeometry: covering_spatial
--   ttext: covering_timeOnly
